server:
  port: 9300

spring:
  application:
    name: market-cloud-gateway
  #网关的配置
  cloud:
    gateway:
      routes: #配置路由
        - id: service-page-router
#          uri: http://127.0.0.1:9100
          uri: lb://market-service-page
          predicates: #当断言成功后，交给某一个微服务处理时使用的是转发
            - Path=/page/**
        - id: service-product-router
#          uri: http://127.0.0.1:9000 #,http://127.0.0.1:9001
          uri: lb://market-service-product
          predicates: #当断言成功后，交给某一个微服务处理时使用的是转发
              - Path=/product/**
          filters: # http://127.0.0.1:9300/product/service/port --> /service/port --> 商品微服务
            - StripPrefix=1 #去掉uri中的第一部分，所以就要求我们通过网关访问的时候，把uri 的第一部分设置为product，从uri的第二部分开始才是真正的uri

eureka:
  client:
    service-url: # eureka server的路径  将项目注册到eureka
      defaultZone: http://localhost:9200/eureka/
    instance:
      #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
      prefer-ip-address: true
      #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
      instance-id: ${spring.cloud.client.ip- address}:${spring.application.name}:${server.port}:@project.version@