#Eureka server服务端口
server:
  port: 9200
spring:
  application:
    name: market-cloud-eureka  # 应用名称，会在Eureka中作为服务的id标识 （serviceId）

eureka:
  instance:
    hostname: localhost # 当前eureka的主机名
  client:
    service-url:  # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://localhost:9200/eureka
    register-with-eureka: false # 自己就是服务不需要注册自己
    fetch-registry: false #自己就是服务不需要从Eureka Server获取服务信息,默认为true，置 为false
